CREATE TABLE `backup_users` (
 `id` int(24) unsigned NOT NULL AUTO_INCREMENT,
 `user_id` int(24) unsigned NOT NULL,
 `nik` varchar(16) NOT NULL,
 `phone_no` varchar(100) NOT NULL,
 `email` varchar(100) NOT NULL,
 `name` varchar(100) NOT NULL,
 `status` enum('pending','active','inactive','banned') NOT NULL DEFAULT 'pending',
 `type` enum('agent','nonagent') NOT NULL DEFAULT 'agent',
 `ref_code` varchar(32) NOT NULL,
 `pending_balance` int(24) unsigned NOT NULL DEFAULT 0,
 `active_balance` int(24) unsigned NOT NULL DEFAULT 0,
 `count_referral` int(4) NOT NULL DEFAULT 0,
 `photo_id` varchar(100) DEFAULT NULL,
 `phone_no_verified` enum('y','n') NOT NULL DEFAULT 'n',
 `email_verified` enum('y','n') NOT NULL DEFAULT 'n',
 `nik_verified` enum('y','n') NOT NULL DEFAULT 'n',
 `submission` enum('y','n') NOT NULL DEFAULT 'n',
 `notification_token` varchar(100) DEFAULT NULL,
 `pin` varchar(255) DEFAULT NULL,
 `created_at` datetime NOT NULL,
 `updated_at` datetime NOT NULL,
 `deleted_at` datetime DEFAULT NULL,
 `backup_at` datetime NOT NULL,
 PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `backup_user_balance` (
 `id` int(24) unsigned NOT NULL AUTO_INCREMENT,
 `user_balance_id` int(24) unsigned NOT NULL,
 `user_id` int(24) unsigned NOT NULL,
 `currency` enum('idr','poin') NOT NULL DEFAULT 'idr',
 `currency_amount` int(12) unsigned NOT NULL,
 `convertion` int(12) unsigned NOT NULL DEFAULT 1,
 `amount` int(12) unsigned NOT NULL,
 `type` enum('bonus','transaction','withdraw') NOT NULL DEFAULT 'bonus',
 `cashflow` enum('in','out') NOT NULL DEFAULT 'in',
 `check_id` int(24) DEFAULT NULL,
 `from_user_id` int(24) DEFAULT NULL,
 `status` tinyint(2) NOT NULL DEFAULT 1 COMMENT '1 = sukses, 2 = pending, 3 = failed',
 `notes` varchar(255) DEFAULT NULL,
 `created_at` datetime NOT NULL,
 `updated_at` datetime NOT NULL,
 `backup_at` datetime NOT NULL,
 PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
