-- 30/08/2021
TRUNCATE TABLE `payment_methods`;
INSERT INTO `payment_methods` (`type`, `name`, `alias_name`, `status`, `created_by`, `created_at`, `updated_by`, `updated_at`) VALUES 
('bank','BCA','Bank Central Asia (BCA)','active','system',NOW(),'system',NOW()),
('bank','MANDIRI','Bank Mandiri','active','system',NOW(),'system',NOW()),
('bank','BRI','Bank Rakyat Indonesia (BRI)','active','system',NOW(),'system',NOW()),
('bank','BNI','Bank Negara Indonesia (BNI)','active','system',NOW(),'system',NOW()),
('bank','CIMB','Bank CIMB Niaga','active','system',NOW(),'system',NOW()),
('bank','DANAMON','Bank Danamon','active','system',NOW(),'system',NOW()),
('bank','PERMATA','Bank Permata','active','system',NOW(),'system',NOW()),
('bank','PANIN','Bank Panin','active','system',NOW(),'system',NOW()),
('bank','ANGLOMAS','Anglomas International Bank','active','system',NOW(),'system',NOW()),
('bank','BANGKOK','Bangkok Bank','active','system',NOW(),'system',NOW()),
('bank','AGRIS','Bank Agris','active','system',NOW(),'system',NOW()),
('bank','SINARMAS','Bank Sinarmas','active','system',NOW(),'system',NOW()),
('bank','AGRONIAGA','Bank BRI Agroniaga','active','system',NOW(),'system',NOW()),
('bank','ANDARA','Bank Andara','active','system',NOW(),'system',NOW()),
('bank','ANZ','Bank ANZ Indonesia','inactive','system',NOW(),'system',NOW()),
('bank','ARTHA','Bank Artha Graha International','active','system',NOW(),'system',NOW()),
('bank','ARTOS','Bank Artos Indonesia','active','system',NOW(),'system',NOW()),
('bank','BISNIS_INTERNASIONAL','Bank Bisnis Internasional','active','system',NOW(),'system',NOW()),
('bank','BJB','Bank BJB','active','system',NOW(),'system',NOW()),
('bank','BJB_SYR','Bank BJB Syariah','active','system',NOW(),'system',NOW()),
('bank','BNI_SYR','Bank BNI Syariah','active','system',NOW(),'system',NOW()),
('bank','BNP_PARIBAS','Bank BNP Paribas','active','system',NOW(),'system',NOW()),
('bank','BUKOPIN','Bank Bukopin','active','system',NOW(),'system',NOW()),
('bank','BUMI_ARTA','Bank Bumi Arta','active','system',NOW(),'system',NOW()),
('bank','CAPITAL','Bank Capital Indonesia','active','system',NOW(),'system',NOW()),
('bank','BCA_SYR','Bank Central Asia (BCA) Syariah','active','system',NOW(),'system',NOW()),
('bank','CHINATRUST','Bank Chinatrust Indonesia','active','system',NOW(),'system',NOW()),
('bank','CIMB_UUS','Bank CIMB Niaga UUS','active','system',NOW(),'system',NOW()),
('bank','COMMONWEALTH','Bank Commonwealth','active','system',NOW(),'system',NOW()),
('bank','DANAMON_UUS','Bank Danamon UUS','active','system',NOW(),'system',NOW()),
('bank','DBS','Bank DBS Indonesia','active','system',NOW(),'system',NOW()),
('bank','DINAR_INDONESIA','Bank Dinar Indonesia','active','system',NOW(),'system',NOW()),
('bank','DKI','Bank DKI','active','system',NOW(),'system',NOW()),
('bank','DKI_UUS','Bank DKI UUS','active','system',NOW(),'system',NOW()),
('bank','FAMA','Bank Fama International','active','system',NOW(),'system',NOW()),
('bank','GANESHA','Bank Ganesha','active','system',NOW(),'system',NOW()),
('bank','HANA','Bank Hana','active','system',NOW(),'system',NOW()),
('bank','HARDA_INTERNASIONAL','Bank Harda Internasional','active','system',NOW(),'system',NOW()),
('bank','HIMPUNAN_SAUDARA','Bank Himpunan Saudara 1906','active','system',NOW(),'system',NOW()),
('bank','ICBC','Bank ICBC Indonesia','active','system',NOW(),'system',NOW()),
('bank','INA_PERDANA','Bank Ina Perdania','active','system',NOW(),'system',NOW()),
('bank','INDEX_SELINDO','Bank Index Selindo','active','system',NOW(),'system',NOW()),
('bank','JASA_JAKARTA','Bank Jasa Jakarta','active','system',NOW(),'system',NOW()),
('bank','KESEJAHTERAAN_EKONOMI','Bank Kesejahteraan Ekonomi','active','system',NOW(),'system',NOW()),
('bank','MASPION','Bank Maspion Indonesia','active','system',NOW(),'system',NOW()),
('bank','MAYAPADA','Bank Mayapada International','active','system',NOW(),'system',NOW()),
('bank','MAYBANK_SYR','Bank Maybank Syariah Indonesia','active','system',NOW(),'system',NOW()),
('bank','MAYORA','Bank Mayora','active','system',NOW(),'system',NOW()),
('bank','MEGA','Bank Mega','active','system',NOW(),'system',NOW()),
('bank','MESTIKA_DHARMA','Bank Mestika Dharma','active','system',NOW(),'system',NOW()),
('bank','MIZUHO','Bank Mizuho Indonesia','active','system',NOW(),'system',NOW()),
('bank','MNC_INTERNASIONAL','Bank MNC Internasional','active','system',NOW(),'system',NOW()),
('bank','MUAMALAT','Bank Muamalat Indonesia','active','system',NOW(),'system',NOW()),
('bank','MULTI_ARTA_SENTOSA','Bank Multi Arta Sentosa','active','system',NOW(),'system',NOW()),
('bank','NATIONALNOBU','Bank Nationalnobu','active','system',NOW(),'system',NOW()),
('bank','NUSANTARA_PARAHYANGAN','Bank Nusantara Parahyangan','active','system',NOW(),'system',NOW()),
('bank','OCBC','Bank OCBC NISP','active','system',NOW(),'system',NOW()),
('bank','OCBC_UUS','Bank OCBC NISP UUS','active','system',NOW(),'system',NOW()),
('bank','BAML','Bank of America Merill-Lynch','active','system',NOW(),'system',NOW()),
('bank','BOC','Bank of China (BOC)','active','system',NOW(),'system',NOW()),
('bank','INDIA','Bank of India Indonesia','active','system',NOW(),'system',NOW()),
('bank','TOKYO','Bank of Tokyo Mitsubishi UFJ','active','system',NOW(),'system',NOW()),
('bank','PANIN_SYR','Bank Panin Syariah','active','system',NOW(),'system',NOW()),
('bank','PERMATA_UUS','Bank Permata UUS','active','system',NOW(),'system',NOW()),
('bank','RABOBANK','Bank Rabobank International Indonesia','active','system',NOW(),'system',NOW()),
('bank','RESONA','Bank Resona Perdania','active','system',NOW(),'system',NOW()),
('bank','ROYAL','Bank Royal Indonesia','active','system',NOW(),'system',NOW()),
('bank','SAHABAT_SAMPOERNA','Bank Sahabat Sampoerna','active','system',NOW(),'system',NOW()),
('bank','SBI_INDONESIA','Bank SBI Indonesia','active','system',NOW(),'system',NOW()),
('bank','MITSUI','Bank Sumitomo Mitsui Indonesia','active','system',NOW(),'system',NOW()),
('bank','BRI_SYR','Bank Syariah BRI','active','system',NOW(),'system',NOW()),
('bank','BUKOPIN_SYR','Bank Syariah Bukopin','active','system',NOW(),'system',NOW()),
('bank','MANDIRI_SYR','Bank Syariah Mandiri','active','system',NOW(),'system',NOW()),
('bank','MEGA_SYR','Bank Syariah Mega','active','system',NOW(),'system',NOW()),
('bank','BTN','Bank Tabungan Negara (BTN)','active','system',NOW(),'system',NOW()),
('bank','BTN_UUS','Bank Tabungan Negara (BTN) UUS','active','system',NOW(),'system',NOW()),
('bank','TABUNGAN_PENSIUNAN_NASIONAL','Bank Tabungan Pensiunan Nasional','active','system',NOW(),'system',NOW()),
('bank','UOB','Bank UOB Indonesia','active','system',NOW(),'system',NOW()),
('bank','VICTORIA_INTERNASIONAL','Bank Victoria Internasional','active','system',NOW(),'system',NOW()),
('bank','VICTORIA_SYR','Bank Victoria Syariah','active','system',NOW(),'system',NOW()),
('bank','WOORI','Bank Woori Indonesia','active','system',NOW(),'system',NOW()),
('bank','YUDHA_BHAKTI','Bank Yudha Bhakti','active','system',NOW(),'system',NOW()),
('bank','ACEH','BPD Aceh','active','system',NOW(),'system',NOW()),
('bank','ACEH_UUS','BPD Aceh UUS','active','system',NOW(),'system',NOW()),
('bank','BALI','BPD Bali','active','system',NOW(),'system',NOW()),
('bank','BENGKULU','BPD Bengkulu','active','system',NOW(),'system',NOW()),
('bank','DAERAH_ISTIMEWA','BPD Daerah Istimewa Yogyakarta (DIY)','active','system',NOW(),'system',NOW()),
('bank','DAERAH_ISTIMEWA_UUS','BPD Daerah Istimewa Yogyakarta (DIY) UUS','active','system',NOW(),'system',NOW()),
('bank','JAMBI','BPD Jambi','active','system',NOW(),'system',NOW()),
('bank','JAMBI_UUS','BPD Jambi UUS','active','system',NOW(),'system',NOW()),
('bank','JAWA_TENGAH','BPD Jawa Tengah','active','system',NOW(),'system',NOW()),
('bank','JAWA_TENGAH_UUS','BPD Jawa Tengah UUS','active','system',NOW(),'system',NOW()),
('bank','JAWA_TIMUR','BPD Jawa Timur','active','system',NOW(),'system',NOW()),
('bank','JAWA_TIMUR_UUS','BPD Jawa Timur UUS','active','system',NOW(),'system',NOW()),
('bank','KALIMANTAN_BARAT','BPD Kalimantan Barat','active','system',NOW(),'system',NOW()),
('bank','KALIMANTAN_BARAT_UUS','BPD Kalimantan Barat UUS','active','system',NOW(),'system',NOW()),
('bank','KALIMANTAN_SELATAN','BPD Kalimantan Selatan','active','system',NOW(),'system',NOW()),
('bank','KALIMANTAN_SELATAN_UUS','BPD Kalimantan Selatan UUS','active','system',NOW(),'system',NOW()),
('bank','KALIMANTAN_TENGAH','BPD Kalimantan Tengah','active','system',NOW(),'system',NOW()),
('bank','KALIMANTAN_TIMUR','BPD Kalimantan Timur','active','system',NOW(),'system',NOW()),
('bank','KALIMANTAN_TIMUR_UUS','BPD Kalimantan Timur UUS','active','system',NOW(),'system',NOW()),
('bank','LAMPUNG','BPD Lampung','active','system',NOW(),'system',NOW()),
('bank','MALUKU','BPD Maluku','active','system',NOW(),'system',NOW()),
('bank','NUSA_TENGGARA_BARAT','BPD Nusa Tenggara Barat','active','system',NOW(),'system',NOW()),
('bank','NUSA_TENGGARA_BARAT_UUS','BPD Nusa Tenggara Barat UUS','active','system',NOW(),'system',NOW()),
('bank','NUSA_TENGGARA_TIMUR','BPD Nusa Tenggara Timur','active','system',NOW(),'system',NOW()),
('bank','PAPUA','BPD Papua','active','system',NOW(),'system',NOW()),
('bank','RIAU_DAN_KEPRI','BPD Riau Dan Kepri','active','system',NOW(),'system',NOW()),
('bank','RIAU_DAN_KEPRI_UUS','BPD Riau Dan Kepri UUS','active','system',NOW(),'system',NOW()),
('bank','SULAWESI','BPD Sulawesi Tengah','active','system',NOW(),'system',NOW()),
('bank','SULAWESI_TENGGARA','BPD Sulawesi Tenggara','active','system',NOW(),'system',NOW()),
('bank','SULSELBAR','BPD Sulselbar','active','system',NOW(),'system',NOW()),
('bank','SULSELBAR_UUS','BPD Sulselbar UUS','active','system',NOW(),'system',NOW()),
('bank','SULUT','BPD Sulut','active','system',NOW(),'system',NOW()),
('bank','SUMATERA_BARAT','BPD Sumatera Barat','active','system',NOW(),'system',NOW()),
('bank','SUMATERA_BARAT_UUS','BPD Sumatera Barat UUS','active','system',NOW(),'system',NOW()),
('bank','SUMSEL_DAN_BABEL','BPD Sumsel Dan Babel','active','system',NOW(),'system',NOW()),
('bank','SUMSEL_DAN_BABEL_UUS','BPD Sumsel Dan Babel UUS','active','system',NOW(),'system',NOW()),
('bank','SUMUT','BPD Sumut','active','system',NOW(),'system',NOW()),
('bank','SUMUT_UUS','BPD Sumut UUS','active','system',NOW(),'system',NOW()),
('bank','CENTRATAMA','Centratama Nasional Bank','active','system',NOW(),'system',NOW()),
('bank','CITIBANK','Citibank','active','system',NOW(),'system',NOW()),
('bank','DEUTSCHE','Deutsche Bank','active','system',NOW(),'system',NOW()),
('bank','HSBC','HSBC Indonesia (formerly Bank Ekonomi Raharja)','active','system',NOW(),'system',NOW()),
('bank','HSBC_UUS','Hongkong and Shanghai Bank Corporation (HSBC) UUS','active','system',NOW(),'system',NOW()),
('bank','JPMORGAN','JP Morgan Chase Bank','active','system',NOW(),'system',NOW()),
('bank','PRIMA_MASTER','Prima Master Bank','active','system',NOW(),'system',NOW()),
('bank','RBS','Royal Bank of Scotland (RBS)','active','system',NOW(),'system',NOW()),
('bank','STANDARD_CHARTERED','Standard Charted Bank','active','system',NOW(),'system',NOW()),
('bank','MITRA_NIAGA','Bank Mitra Niaga','active','system',NOW(),'system',NOW()),
('bank','ARTA_NIAGA_KENCANA','Bank Arta Niaga Kencana','active','system',NOW(),'system',NOW()),
('bank','MAYBANK','Bank Maybank','active','system',NOW(),'system',NOW()),
('bank','SHINHAN','Bank Shinhan Indonesia (formerly Bank Metro Express)','active','system',NOW(),'system',NOW()),
('bank','MANDIRI_TASPEN','Mandiri Taspen Pos (formerly Bank Sinar Harapan Bali)','active','system',NOW(),'system',NOW()),
('bank','EXIMBANK','Indonesia Eximbank (formerly Bank Ekspor Indonesia)','active','system',NOW(),'system',NOW()),
('bank','QNB_INDONESIA','Bank QNB Indonesia (formerly Bank QNB Kesawan)','active','system',NOW(),'system',NOW()),
('bank','BANTEN','BPD Banten (formerly Bank Pundi Indonesia)','active','system',NOW(),'system',NOW()),
('bank','JTRUST','Bank JTrust Indonesia (formerly Bank Mutiara)','active','system',NOW(),'system',NOW()),
('bank','BTPN_SYARIAH','BTPN Syariah (formerly BTPN UUS and Bank Sahabat Purba Danarta)','active','system',NOW(),'system',NOW()),
('bank','CCB','China Construction Bank Indonesia (formerly Bank Antar Daerah and Bank Windu Kentjana International)','active','system',NOW(),'system',NOW()),
('bank','SINARMAS_UUS','Bank Sinarmas UUS','active','system',NOW(),'system',NOW()),
('bank','AMAR','Bank Amar Indonesia (formerly Anglomas International Bank)','active','system',NOW(),'system',NOW()),
('bank','WOORI_SAUDARA','Bank Woori Saudara Indonesia 1906 (formerly Bank Himpunan Saudara and Bank Woori Indonesia)','active','system',NOW(),'system',NOW()),
('bank','OKE','Bank Oke Indonesia (formerly Bank Andara)','active','system',NOW(),'system',NOW()),
('emoney','GOPAY','GoPay','active','system',NOW(),'system',NOW()),
('emoney','OVO','OVO','active','system',NOW(),'system',NOW()),
('emoney','MANDIRI_ECASH','Mandiri E-Cash','active','system',NOW(),'system',NOW()),
('emoney','DANA','DANA','active','system',NOW(),'system',NOW()),
('emoney','LINKAJA','LinkAja','active','system',NOW(),'system',NOW()),
('emoney','SHOPEEPAY','ShopeePay','active','system',NOW(),'system',NOW()),
('bank','BSI','Bank Syariah Indonesia (BSI)','active','system',NOW(),'system',NOW());

